# Generated by Django 5.0.14 on 2025-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('abstract', models.TextField()),
                ('file', models.CharField(max_length=500)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-bookmarked_at'],
                'indexes': [models.Index(fields=['user_id', '-bookmarked_at'], name='bookmarks_user_id_128234_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('query', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('relevant', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='feedback_user_id_88c7db_idx'), models.Index(fields=['-created_at'], name='feedback_created_d6e06a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('main_query', models.TextField()),
                ('all_queries', models.JSONField(default=list)),
                ('conversation_data', models.JSONField(default=dict)),
                ('sources_count', models.IntegerField(default=0)),
                ('conversation_length', models.IntegerField(default=1)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('date_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'research_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='research_hi_user_id_3a9406_idx')],
            },
        ),
    ]
