# Generated by Django 5.0.14 on 2025-11-22 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmarks_user_id_128234_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_user_id_88c7db_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_created_d6e06a_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchhistory',
            name='research_hi_user_id_3a9406_idx',
        ),
        migrations.RemoveField(
            model_name='researchhistory',
            name='main_query',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchhistory',
            name='query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='all_queries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='conversation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='conversation_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='date_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='session_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='sources_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhistory',
            name='user_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user_id', 'file')},
        ),
    ]
