# Generated by Django 5.0.14 on 2025-12-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0002_adminuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='user_email', max_length=50, unique=True)),
                ('password_hash', models.CharField(db_column='user_password_hash', max_length=200)),
                ('full_name', models.CharField(blank=True, db_column='user_full_name', max_length=100, null=True)),
                ('username', models.CharField(db_column='user_username', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='user_created_at')),
                ('last_login', models.DateTimeField(blank=True, db_column='user_last_login', null=True)),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('staff', 'Staff'), ('admin', 'Admin')], db_column='user_role', default='user', max_length=50)),
            ],
            options={
                'db_table': 'user_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(db_column='session_ID', primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(db_column='session_is_anonymous', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='session_created_at')),
                ('last_seen', models.DateTimeField(auto_now=True, db_column='session_last_seen')),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, db_column='USERS_ACCOUNTS_user_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rag_api.useraccount')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
