# Generated by Django 5.0.14 on 2025-12-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0003_useraccount_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.OneToOneField(blank=True, db_column='USERS_ACCOUNTS_user_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='rag_api.useraccount'),
        ),
    ]
