# Generated by Django 5.0.14 on 2026-01-22 05:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0004_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='document_file',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500, unique=True)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('school', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materials',
                'indexes': [models.Index(fields=['file'], name='materials_file_706a2a_idx'), models.Index(fields=['-created_at'], name='materials_created_35dc44_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(db_index=True, max_length=500)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'material_views',
                'indexes': [models.Index(fields=['file'], name='material_vi_file_280caa_idx'), models.Index(fields=['-viewed_at'], name='material_vi_viewed__5f2d37_idx'), models.Index(fields=['user_id'], name='material_vi_user_id_8ac323_idx')],
            },
        ),
    ]
