# Generated by Django 5.0.14 on 2026-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0005_feedback_document_file_material_materialview'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Issue', 'Issue'), ('For Improvement', 'For Improvement')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_doable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
