# Generated by Django 5.0.14 on 2026-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0006_feedback_admin_remarks_feedback_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_remarks',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feasibility_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='validity_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
