# Generated by Django 5.0.14 on 2026-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0008_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(db_column='user_is_active', default=True),
        ),
    ]
