# Generated by Django 5.0.14 on 2026-02-09 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0011_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.TextField(db_index=True)),
                ('session_id', models.TextField(blank=True, db_index=True, null=True)),
                ('consent_given', models.BooleanField(db_index=True, default=False)),
                ('client_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Business', 'Business'), ('Government', 'Government (Employee/Agency)')], max_length=50)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=50)),
                ('age', models.CharField(choices=[('10 and below', '10 years old and below'), ('11-15', '11 - 15 years old'), ('16-20', '16 - 20 years old'), ('21-25', '21 - 25 years old'), ('26-30', '26 - 30 years old'), ('31-35', '31 - 35 years old'), ('36-40', '36 - 40 years old'), ('41-45', '41 - 45 years old'), ('46-50', '46 - 50 years old'), ('51-55', '51 - 55 years old'), ('56-60', '56 - 60 years old'), ('61 and above', '61 years old and above')], max_length=50)),
                ('region', models.CharField(choices=[('NCR', '[NCR] National Capital Region'), ('CAR', '[CAR] Cordillera Administrative Region'), ('R01', '[R01] Region 1 (Ilocos Region)'), ('R02', '[R02] Region 2 (Cagayan Valley Region)'), ('R03', '[R03] Region 3 (Central Luzon Region)'), ('R4A', '[R4A] Region 4A (CALABARZON Region)'), ('R4B', '[R4B] Region 4B (MIMAROPA Region)'), ('R05', '[R05] Region 5 (Bicol Region)'), ('R06', '[R06] Western Visayas Region'), ('R07', '[R07] Central Visayas Region'), ('R08', '[R08] Eastern Visayas Region'), ('R09', '[R09] Zamboanga Peninsula Region'), ('R10', '[R10] Northern Mindanao Region'), ('R11', '[R11] Davao Region'), ('R12', '[R12] SOCCSKSARGEN Region'), ('R13', '[R13] Caraga Administrative Region'), ('BARMM', '[BARMM] Bangsamoro Autonomous Region in Muslim Mindanao'), ('N/A', '[N/A] Not Applicable (Overseas)')], max_length=50)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('DOST Employee', 'DOST Employee'), ('Other Government Employee', 'Other Government Employee'), ('Librarian/Library Staff', 'Librarian/Library Staff'), ('Teaching Personnel', 'Teaching Personnel'), ('Administrative Personnel', 'Administrative Personnel'), ('Researcher', 'Researcher')], max_length=100)),
                ('litpath_rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('missing_content', models.TextField(blank=True, null=True)),
                ('message_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'csm_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
