# Generated by Django 5.0.14 on 2026-02-11 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0012_csm_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmfeedback',
            name='admin_category',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Issue', 'Issue'), ('For Improvement', 'For Improvement')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='feasibility_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='is_doable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='csmfeedback',
            name='validity_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file', models.CharField(db_index=True, max_length=500)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('is_relevant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_ratings',
                'indexes': [models.Index(fields=['file'], name='material_ra_file_2b0dc7_idx'), models.Index(fields=['rating'], name='material_ra_rating_c7346e_idx')],
                'unique_together': {('user_id', 'file')},
            },
        ),
    ]
