# Generated by Django 5.0.14 on 2026-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0013_csmfeedback_admin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmfeedback',
            name='admin_category',
            field=models.CharField(blank=True, help_text='e.g. Bug, Feature Request, Content Request, Compliment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
