# Generated by Django 5.0.14 on 2026-02-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0014_alter_csmfeedback_admin_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhistory',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='consent_given',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
