# Generated by Django 5.0.14 on 2026-02-16 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0015_researchhistory_response_time_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('citation_style', models.CharField(max_length=50)),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_copies', to='rag_api.material')),
            ],
            options={
                'ordering': ['-copied_at'],
            },
        ),
    ]
